image: python:3-slim
before_script:
    - pip3 install flake8
    - pip3 install graphviz

stages:
    - test
    - static_analysis
variables:
    PYTHON: "python3"
static_analysis:
    stage: static_analysis
    script:
        - pip3 install flake8
        - flake8 --max-line-length=120 src/*.py
        - flake8 --max-line-length=120 test/*.py
test:
    stage: test
    script:
        - echo "test started..."
        - cd tests
        - python3 main.py
        - echo "Example test over."



