image: python:3-slim
before_script:
    - pip3 install -r requirements.txt
stages:
    - static_analysis
    - test

static_analysis:
    stage: static_analysis
    script:
        - flake8  src/*.py tests/*.py
test:
    stage: test
    script:
        - echo "test started..."
        - python3 -m unittest discover -s tests/
        - echo "Example test over."



