image: python:3-slim
before_script:
    - pip3 install flake8
    - pip3 install graphviz
    - pip3 install mypy
stages:
    - static_analysis
    - test
variables:
    PYTHON: "python3"
static_analysis:
    stage: static_analysis
    script:
        - flake8 --max-line-length=120 src/*.py
        - mypy src/*.py
        - mypy tests/*.py
test:
    stage: test
    script:
        - echo "test started..."
        - cd tests
        - python3 main.py config
        - echo "Example test over."



