image: python:3-slim
before_script:
    - pip install -r requirements.txt
stages:
    - static_analysis
    - test

static_analysis:
    stage: static_analysis
    script:
        - flake8 --max-line-length=120 src/*.py
test:
    stage: test
    script:
        - echo "test started..."
        - cd tests
        - python -m unittest -v main.py
        - echo "Example test over."



