image: python:3-slim
before_script:
    - apt update
    - apt install -y python3-pip
stages:
    - static_analysis
    - test
variables:
    PYTHON: "python3"
static_analysis:
    stage: static_analysis
    script:
        - pip3 install flake8
        - flake8 --max-line-length=120 src/*.py
        - flake8 --max-line-length=120 test/*.py
test:
    stage: test
    script:
        - echo "test started..."
        - cd tests
        - python3 main.py
        - echo "Example test over."



