image: python:3-slim
before_script:
    - pip3 install flake8
stages:
    - static_analysis
variables:
    PYTHON: "python3"
static_analysis:
    stage: static_analysis
    script:
        - flake8 --max-line-length=120 src/*.py

